language: java
jdk:
  - openjdk11
env:
  global:
    - HUGO_VERSION=0.48
    - BOOTIQUE_DOCS_VERSION=v1.0.0-beta-5
install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - sudo dpkg -i "hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - nvm install 8
  - wget "https://github.com/bootique/bootique-docs/releases/download/${BOOTIQUE_DOCS_VERSION}/bootique-docs.zip"
  - unzip bootique-docs.zip
script:
  - cd ./app && yarn run build
  - cd ../scripts && yarn run build
  - cd ../ && ./bootique-docs/bin/bootique-docs --config=docs.yml
  - hugo
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
cache:
  - yarn
